/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b6dfb43f-468c-4097-8514-604bd1295341",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_TJQW5QRHe",
    "aws_user_pools_web_client_id": "1njhe68bef1usec72udq6o3icf",
    "oauth": {}
};


export default awsmobile;
